### ISSUE TITLE
Bug in OLC short code recovery

### ISSUE THREAD

**Issue by drinckes** [wnameless/plus_codes-ruby#1]
Hi - we recently discovered a bug in the recover or recoverNearest algorithm for Open Location Code. We've fixed it in the libraries in the main github project. To see what changes we made, you can refer to [this issue](https://github.com/google/open-location-code/issues/37), and it's linked pull request, for details on how you can make the fix in your own code.

Thanks for using OLC!

**Comment by wnameless** [comment]
This Ruby implementation has been tested with the example you provided.
It seems that everything is fine with current version.
You can check it by yourself.
Thanks for the mention anyway.
